client-side/conventions/commits.md
@vperezma Please review, Thanks!
=> feat(commits)

QA/bug_reporting/bug_reporting.md
Changes tags to labels per Lino's request. Fix #17
=> feat(QA reporting): Changes tags to labels

client-side/css/SCSS.md
Please review or suggest edits
=> feat(scss): Add .md file for scss in css/. Still haven't done LESS

client-side/javascript/README.md
Gotta start somewhere
Closes #32
=> docs(js): Add modules, es6, and promises standards to repo

client-side/framework/angular/deploy/README.md
Successfully deploying using aot.
=> feat(deploy): notes on deploying angular apps

conventions/code-reviews.md
=> fix(code-reviews): Fixes whitespace issues plus 'recieve' to 'receive'

native/README.md
Fixed relative URLs in native folder readme.
=> fix(native readme): Fixed relative URLs in native folder readme.

server-side/framework/README.md, server-side/framework/php/README.md, server-side/framework/php/laravel/README.md, server-side/framework/php/laravel/docker-compose.yml, server-side/framework/php/laravel/docker/artisan/Dockerfile, server-side/framework/php/laravel/docker/composer/Dockerfile, server-side/framework/php/laravel/docker/nginx/Dockerfile, server-side/framework/php/laravel/docker/nginx/default.conf, server-side/framework/php/laravel/docker/php-fpm/Dockerfile
This PR will add PHP to the server-side frameworks file structure and add Laravel as a php framework.  I have also included a basic docker setup for Laravel projects and provided documentation for that.  
Closes https://github.com/Shift3/standards-and-practices/issues/71
=> Adds PHP and Laravel into the file structure and necessary Readme's

client-side/framework/README.md, client-side/framework/vue/README.md, client-side/framework/vue/app.js, client-side/framework/vue/bootstrap.js, client-side/framework/vue/classes/Errors.js, client-side/framework/vue/classes/Form.js, client-side/framework/vue/classes/README.md, client-side/framework/vue/components/Loading-Modal.vue, client-side/framework/vue/components/Modal.vue, client-side/framework/vue/components/README.md, client-side/framework/vue/components/Tab.vue, client-side/framework/vue/components/Tabs.vue, client-side/framework/vue/routes.js
I have added Vue into the file repo file structure along with added/updated the appropriate README's.  I also included some boilerplate files I use along with reusable components/classes that I pull into most of my projects.  Not sure if this is the best place to have those files, but since this is our only place to share files like that, I included them.  Let me know if you want me to resubmit without the extra files.
=> Adds Vue to client-side frameworks, and includes some boilerplate and reusable files

aws/cloudfront-set-up.sh, aws/readme.md, aws/s3-cloudfront-script.md
Here's the Bash script that I had mentioned on Corey's PR (#79).
I had tested this months ago, but I don't expect things to have changed since then.
My Bash is rusty, but the script is relatively simple so there shouldn't be any weird stuff. However, if you see anything, let me know.
=> Add Bash script to generate the default S3-Cloudfront environment

code-quality/README.md, code-quality/continuous-integration/README.md, code-quality/continuous-integration/circle_ci_config.yml
There's still a few things that I need to update (such as company account access), but it should provide us with a template that we can use to start using CI after tomorrow's talk.
Closes #89
=> Initial documentation about CI and how to set it up

native/react-native/rn-by-example/README.md, native/react-native/rn-by-example/basicLayoutClass.js, native/react-native/rn-by-example/basicLayoutFunctional.js
This is the beginning of the RN By Example guide.  Only two lessons for now, but more will be coming.
=> Rn by example

docker/bash-scripts/ecr-script/docker-ecr.sh, docker/bash-scripts/ecr-script/readme.md, docker/readme.md
Be sure to critique the verbiage here, I never know how to word these things. Also please try this out yourselves and let me know how well it works!
=> feat(docker): Adds image deployment bash script

code-quality/accessibility/README.md
I'll go into further detail on the various aspects of accessibility compliance in subsequent PRs, this is just a basic introduction for now for me to branch off of in the future.
=> Basic accessibility write-up

.github/CODEOWNERS
1. Add @carlosvargas and @DropsOfSerenity and remove old owners.
After this is done, we can implement branch protection for merge requests.
Simple! Just add/remove the names to the file.
We had this established already, but I forgot to update it! You can find the official [docs here](https://github.blog/2017-07-06-introducing-code-owners/). Thanks to @carlosvargas for the reminder!
=> chore(owners): Update code owners

git-and-github/project-setup.md
1. Change the documentation for project board setup to match @coreyshuman 's suggestions in issue #115 
Match Shift3's new process
Using Github's automation and tooling.
Closes #115
=> fix(projectBoards): Add new rules per issue #115

native/xamarin/README.md
1. Added root Xamarin document
Introduce people to general Xamarin best practices and some Shift3 work employing Xamarin Forms and Xamarin Shell
closes #122
closes https://github.com/Shift3/sinclair-scanner-application/issues/141
=> Chore / Xamarin Intro Text

native/react-native/rn-by-example/README.md
As the title says, this PR adds the link to the RN boilerplate app.
=> docs(rn): Adds link to boilerplate app

QA/README.md, QA/acceptance-testing/README.md, README.md
- To provide a guide on how to and why to implement acceptance testing.
=> docs(QA): add acceptance testing guide

best-practices/development-tools/validation/README.md
This is a new PR that follows #130 and duplicates it to introduce this file to the new code structure.
=> feat(validation): add readme for regex validation to new repo structure

best-practices/server-side/framework/node/nodemailer/README.md
1. Sets guidelines for using HTML with Nodemailer.
=> feat(nodemailer): best practices for nodemailer

standards/acceptance-testing.md
1. Updated the header name to make it consistent and clear.
2. Improved phrasing in standard.
The standard now makes the purpose of the standard clear.
Closes #150.
=> docs(acceptance-testing): add purpose to acceptance testing standard

standards/qa-process.md
- Fix formatting for email requirements
- Add billable question to email
Added details to the QA process which address confusion / miscommunication we've had in practice.
We needed a better way to communicate and track between billable and non-billable QA time.
Closes #148
=> docs(qa process): fix formatting and add billable question

best-practices/development-tools/continuous-integration/react-native-expo.md
1. Fixes a couple of sentence structure and spelling issues.
Went over page and tried out the instructions. Found a couple of spelling issues.
References: #165
=> fix(ci-react): spelling and grammar

best-practices/database/README.md
1. Added link and basic info on Ubuntu + PostgreSQL install
Using provided resource from known good source. It may be difficult to create a README page for each version of Ubuntu ourselves. Digital Ocean provides a good example for each version of Ubuntu that they keep up to date. 
References #59
=> feat(database-postgreSQL): Digital Ocean instructions

best-practices/native/react-native/deployment/ios/README.md
1. Line 59 - typo - "distribute" not "distrube"
2. Line 77 - typo - "Manage" not "Manange"
_How does this change address the problem?_
Fixes typos
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_
_If this closes an issue, name it here. If it doesn't, remove this line_
=> docs(typo): 2 typos

best-practices/database/README.md
1. Basic setup for mysql for ubuntu
Digital Ocean is one of the better resources for Linux installs. 
I think we will want to go over Mac OS installs as well, since thats what we use.
References #59
=> feature(setup-databases): Setup mysql for ubuntu

README.md
1. Add links to main README for Visual studio code, visual studio, and Frontend Masters
References #95
=> feat(README): Add basic links to visual studio tooling and FM

standards/code-reviews.md, standards/contributing.md, standards/readme-guidelines.md
1. Removed or replaced missing links to standards readmes
More accurate links and cuts down on new developer confusion.
Closes #168
=> fix(standards): Remove or replace broken links

presentations/README.md
1. Adds the new link for Google Sheet
2. Adds our new subtitle to the README
I replaced the link to our presentation sign-up sheet with the correct one & added an `H3` that holds the new subtitle of our meeting.
n/a
Closes #186
=> S&P meeting link update

.circleci/config.yml, best-practices/native/react-native/expo/certificates/README.md, best-practices/native/react-native/expo/upgrade/README.md, best-practices/server-side/framework/php/laravel/README.md, standards/code-versioning.md
1. Fix Circleci awesomebot runs to include dups and allowlist.
2. Internal private repos show up as a 404 within awesomebot. Temporary solution is a allowlist that contains Shift3 private repos. Long term solution will need to be discussed outside this PR (or within, im not picky!)
3. Changed any API and old documentation to newest api within contexts. If anyone finds something out of place, let me know please!
Fix links that are 404ing and internal links.  
Closes #162
=> WIP: Fix url redirects

best-practices/native/nativescript/environment.md, best-practices/native/nativescript/evironment.md
1. Create an tutorial to setup environment files in NativeScript
Simplify the way we compile NS projects. That helps in productivity.
Closes #197
=> NativeScript-Angular Environment setup.

best-practices/native/README.md
1. Added corrected links to native development links.
Users can now easily navigate to the corrected links
Outside of this current scope, I think some of these READMEs need to be updated. There is a huge difference between:
https://github.com/Shift3/standards-and-practices/blob/master/best-practices/native/ionic/README.md
and
https://github.com/Shift3/standards-and-practices/tree/master/best-practices/native/xamarin
Closes #195
=> fix(native-development): Fix 404ed links

best-practices/native/nativescript/images.md
1. Create a article to handle images in Nativescript
We spend a lot time resizing images for each screen size device. 
We learn how to do that in the easy way, totally automatized. 
Closes #198
=> Image handle in Nativescript-Angular

standards/README.md, standards/git-commands.md
1. Adds git commands README
2. Adds `git stash` with example/references
By explaining git stash and the concepts behind it, I am hoping to help other developers be more productive when a clean index/working directory is needed as well as switching code between branches for context switching purposes. It also allows the developer to maintain feature specific branches by allowing code changes to not be "lost" when switching between branches.
At the moment, I plan on being as specific as possible with each of these examples, so I will try to be as atomic as possible with these small PRs.
I had to look up a large amount of resources as there is more documentation on rebasing than git stashing.
I'm still looking for a good video tutorial to accommodate visual learning but at the moment, I cant …
=> feature(git-commands): Git commands and git rebase

.github/ISSUE_TEMPLATE/bug_report.md, standards/issue-template.md
1. Add a GitHub issue template for bug reports.
Closes #0201.
=> chore, docs(github): add bug report issue template

best-practices/database/README.md
1. Add Docker instructions from official MS sources 
Speed up a preferred method of installing SQL server and setup.
We have instructions on how to build Postgres and Mysql but not MSSQL. We would at least provide an example docker installation from the official Microsoft source.
References #59
=> Docker instructions for installing MSSQL

best-practices/server-side/framework/node/express/README.md, best-practices/server-side/framework/node/nestjs/README.md
1. Added NestJS as a proposed server framework
To add NestJS as a server framework
Add a new technology to the repo.
visit https://nestjs.com/
_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #223
=> feat(nestjs) finshed .md file

best-practices/client-side/framework/react/README.md
1. Add to list of safe and helpful development plugins
2. Specific to React
Create a location to share helpful plugins used by our development team. Adding a couple of resources commonly used in React. 
This change will give us a centralized location of helpful plugins related to development in React.
- [React Developer Tools](https://github.com/facebook/react/tree/master/packages/react-devtools-extensions)
- [Redux DevTools](https://github.com/zalmoxisus/redux-devtools-extension)
closes #231
=> Helpful Development Plugins - React - Closes #231

.circleci/config.yml, Dangerfile, Gemfile, Gemfile.lock
1. Add Ruby based [Danger](https://danger.systems/ruby/) to the S&P repo 
2. Created Shift3PullRequestBot to create the messages on the fly as per Dangers instructions.
3. Added the `Dangerfile` a ruby based script that allows for certain messages to be auto-created when a Pull Request is made. 
4. `Bundle` now controls dependencies within the CI process instead of base `gem install`.  
When a pull request is created, we have a certain standard within the organization based on this documentation: https://github.com/Shift3/standards-and-practices/blob/main/standards/contributing.md 
We should have some sort of automated script that informs the developer what rules they may be unknowingly violating. It helps everyone by defining each one of these rules formally within the `Dangerfile`, sets …
=> Pull Request description automation

best-practices/database/README.md
1. Add a description on databases
2. Add link to comparison of databases
Users should be able to get more information on databases. 
The linked resource also provides a general non-biased (in my opinion) description of the major databases. 
I tried finding a comparison online that included many of the databses we use at Bitwise. Unfortunately, most of the resources seemed heavily biased and didn't include a nice pro/con setup. 
I didn't get a lot of feedback from the technical discussions channel, so I thought I would throw this out there and see what people think!
Closes #219
=> feature(database): General information on Databases

best-practices/development-tools/accessibility/README.md, best-practices/development-tools/accessibility/WCAG-testing.md, best-practices/native/react-native/deployment/android/README.md, best-practices/native/react-native/deployment/ios/README.md, best-practices/native/react-native/expo/upgrade/README.md
1. Spelling around our READMEs
Improve readability by adding correct spelling.
Fixing spelling errors within READMEs.
Set up my environment with a nifty spell checker: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker and seems to be doing the job.
Closes #165
=> fix(spelling): Quick overview of our spelling

best-practices/client-side/README.md, best-practices/client-side/security/README.md
1. Add page for Client-side security best practices
2. Add XSS docs and how to prevent within Angular, React, and general purpose
3. Add HTML 5 specific security cheat sheet.
Developers should know the basics on client side software security. 
By adding in common links, sources, and examples, developers should be able to understand and avoid common client side XSS security related issues. 
Big thanks to @jecallaway for giving me some great feedback to start this process out!
https://owasp.org/www-project-top-ten is a great resource for all things security (CVE) related. 
This PR is going to be a ongoing string or PRs where we start filling in the missing security docs in the S&P repo. 
I'm not satisfied with the XSS react link: https://www.netsparker.com/blog/web-security/cross-site-script …
=> feature(security): Client security docs

.github/ISSUE_TEMPLATE/epic-issue-template.md
1. Add Epic template
The Boilerplate projects have proven that using Epics are a good thing for projects when they are utilized. 
Developers should have an example of a working Epic template. 
Other sample issue templates:
Sample epic template: https://github.com/ethersphere/user-stories/blob/master/.github/ISSUE_TEMPLATE/epic-template.md
Some great examples: https://github.com/devspace/awesome-github-templates
I would like for a discussion on the content/wording of the template. If anyone has a good idea to add to the template, feel free to chime in! 
Closes #259
=> feature(epic-template): Developers should be able to create epics

standards/qa-process.md
1. Removing Report of Issues
2. Added links for a few items including Compliance Guidelines doc
3. Adding Lighthouse Score to Certificate of Completion
4. Small grammar adjustments 
_Report of Issues was deemed unnecessary on our end so that needs to be removed to prevent future requests. I added a link for the Compliance Guidelines doc so that PM's and developers would also have access to that information. Lighthouse score is being added to the Certificate of Completion so that we can track this in our metrics and so that developers can see how their website scores based on Google Standards._
_Report of Issues option is removed, resources added as links, lighthouse score to be addressed at the end of a project, and grammar has been adjusted._
Closes #269
=> QA SP update 2

best-practices/client-side/framework/react/README.md
1. Includes React Testing Library as a testing library for React
Provide alternative libs
_How does this change address the problem?_
_What needs to be done before testing_
- [] Change database values in x collection to y.
Read the doc
_Describe the research stage_
=> docs(client side frameworks): list React Testing Library for React

best-practices/development-tools/validation/README.md
1. Adds best practices around SES email sending
2. Adds reason behind best practice (SES email bouncing). 
Provide concise info on why its a good idea to use real email addresses for SES emails.
Provide guidance on a known good way of testing emails as well as more info in general on the process.
Closes #318
=> feature(email-validation): Developers should know what SES validation is

best-practices/client-side/framework/react/README.md
1. Added a link to React Hooks Testing Library to the list of testing tools in `standards-and-practices/best-practices/client-side/framework/react/`
Testing custom hooks in React is complicated as you have to write function components solely for testing these hook. The React Hooks Testing Library simplifies testing custom hooks by allowing you to create a simple test harness for React hooks that handles running them within the body of a function component, as well as providing various useful utility functions for updating the inputs and retrieving the outputs of your custom hooks.
1. Go to the `standards-and-practices/best-practices/client-side/framework/react/` directory.
2. Check that there is a link to the React Hooks Testing Library in the list of unit testing tools.
3. Ensure that …
=> doc(react): Add link to React Hooks Testing Library

best-practices/native/react-native/README.md, best-practices/native/react-native/startup/native-code.md, best-practices/native/react-native/training/README.md
1. Creating Docs for React Training.
The purpose of this PR is to add more information about using React/React Native and referencing important features of the Library.
For this PR I had to research the exact definitions of each method and keyword that the library uses as well as determining the most useful changes between ES5 and ES6 to include in the document as well as making sure that encouraging Functional components was just as important as showing how similar problems would be solved with Class Based Components.
Here are some documents I referenced
- [https://medium.com/edonec/state-in-react-an-overview-a182675cee2c](https://medium.com/edonec/state-in-react-an-overview-a182675cee2c)
- [https://github.com/uberVU/react-guide/blob/master/props-vs-state.md](https://github.com/uberVU/rea …
=> Creating docs for React Training

README.md
1. Adds handbook homepage to our S&P
We have been working on the handbook for some time. Everyone should be able to see the progress we made here. 
Add link to handbook homepage.
Closes #000
=> docs(readme): Developers should navigate to the handbook

README.md
1. Added a sub section to the Need help section about problem solving
2. Included an article about problem solving from freecodecamp.
Help developers better problem solve before asking help on tasked issues.
The freecodecamp article gives a general guideline on problem solving
https://www.freecodecamp.org/news/how-to-think-like-a-programmer-lessons-in-problem-solving-d1d8bf1de7d2/
Closes #347
=> docs(problem-solving):include problem solving article to ReadME
