Shift3/standards-and-practices

- README.md
- git-and-github/README.md
- git-and-github/readme-guidelines.md
Shift3 projects are poorly documented, making it difficult for developers to get up and running on an unfamiliar project. Here are some bare-minimum guidelines for documentation which should be included on all Shift3 projects upon creation of the project.
> Added guidelines for readme files on projects

- aws/readme.md
- aws/s3-cloudfront-deployment.md
Something to get newbies to AWS deployments started.
- Created a folder for AWS.
- Added instructions for S3 cloudfront deployment of static sites.
I created these instructions by sitting in on Greg walking Matt H through a deployment from beginning to end.
Additional tasks to do in the future:
- instructions on using `s3` command line tool
- new guide on deploying using elastic beanstalk and `eb` command line tool
- Matt was planning to make gifs of the process and embed them into the guide
> Created aws folder and s3-cloudfront deployment guide

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- git-and-github/ISSUE_TEMPLATE.md
- git-and-github/PULL_REQUEST_TEMPLATE.md
- git-and-github/README.md
1. Adds an issue template 
2. Adds a PR template
Ideally all of our repos from this point on (after presentation) will adopt the use of these templates to make our issue creation and PR summaries more succinct, verbose, and uniform across projects.
By automating the process of scaffolding out the structure of the PR and Issue creation process, this will bring uniformity and more detail to both processes. 
N/A
1. Check the templates to make sure I didn't miss any nice-to-haves
I looked these up over the weekend and they're awesome! I linked to them in issue #113.
Closes #113
> feat(templates): Add PR and issue template for org

- presentations/README.md
1. Adds a readme for accessing the S&P slide decks
The S&P slide deck link was only accessible to employees on the Bitwise Slack channel.
Adds a new folder for information on presentations with a readme containing a link to the slide decks.
> feat(presentations): Adds a readme for accessing the S&P slide decks

- server-side/framework/php/laravel/docker/php-fpm/Dockerfile
1. Update php:7.1-fpm to php:7.2-fpm
2. Update Extensions: BCMath, Ctype, JSON, Mbstring, PDO, Tokenizer, XML 
Change PHP docker settings for Laravel 6.0 requirements. 
Missing required extension "OpenSSL". Conflict for those needing Laravel 5.0 project
Structure change to standard-and-practices framework
> Update php:7.1-fpm to php:7.2-fpm and extensions

- git-and-github/code-reviews.md
1. Specify who should test code as part of PR review (dev team, not external teams)
1. Specify who should merge code after approval (project maintainers only)
1. Address stair-stepped PRs. In general we don't do them at Shift3.
We had a lot of confusion and a few frustrated devs over the last few months related to PR reviews. Addresses the following:
- External team members are not required to pull down and test code as part of a review.
- External team members should not merge code after a review. Only project maintainers should be merging PRs.
- In general we don't do stair-stepped PRs at Shift3. They require lots of pulling and merging by the reviewer to get through the stack of PRs. This would prevent us from easily having external team members review code for which they are …
> docs(code review): Clarify testing and merging as part or review

- .github/ISSUE_TEMPLATE/bugfix.md
There was a tongue-in-cheek phrase in the issue template that has been removed.
> Remove "Code Better"

- best-practices/native/react-native/expo/upgrade/README.md
1. Documented the issues I ran into upgrading the Expo SDK for Listing Alert from version 32 to 36.
2. Threw in a bonus about using `--no-publish` and SDK version 37.
I'm not entirely sure this will be **super** useful since we only have one other application at Shift3 using Expo that hasn't been ejected (currently Secrets Unsealed at v33). That being said, given all the issues we've had thus far upgrading React Native problems, any success story could be worth documenting, even ones rife with peril.
Closes #144
> Expo upgrade process from 32 to 36.

- best-practices/native/react-native/expo/certificates/README.md
1. Added a write up on expired apple credentials, and a little bit about android creds too.
The Listing Alert provisioning profile expired. Renewing it was an adventure. Thanks to @ryekerjh for helping me through it.
I must admit, I'm still a little murky about Apple credentials, so I wanted to brain dump everything I learned for now. If anyone who knows better can correct me on a few things (@ryekerjh), please let me know.
Closes #152
> Expired Apple Credentials (Expo)

- standards/branching.md
1. Add more detail to the git branch standard
2. Add reasoning why a developer would want to use the standard.
Added more detail to the markdown specifying the exact components or a branch and making it explicit (rather than implicit as the docs were before).
Closes #157
> docs(branch-structure): reasoning behind branch standard

- best-practices/server-side/framework/README.md
Adds a little more detail to each described framework. 
All five frameworks/languages have an official tag or description from their main websites. I just added those to the descriptions.
References #160
> docs(framework): add official descriptions

- best-practices/client-side/framework/angular/README.md
- best-practices/development-tools/continuous-integration/angular_config.yml
1. Add MVP Angular + CircleCI specific yml
By adding a known good CircleCI configuration, developers will be able to add CircleCI specific builds and tests to their respective projects. This is the bare minimum to get started. I funny expect this to change in the near future.
Learned that Angular now has a direct build page here: https://angular.io/guide/testing#configure-project-for-circle-ci 
References #94
> feat(angular-circleci): Angular Circleci build and test

- README.md
1. Acceptance Testing link now goes to the correct url
2. Bug Reporting link now goes to the correct url
Fixed links by going through each of the links manually. 
References: #95
> Fix new hire links

- .github/CODEOWNERS
Michael Chrisco will now be the primary codeowner for Standards and Practices. This is part of a larger effort to eventually have a dedicated team to maintain and apply Standards and Practices for the shop, which Chrisco will lead. This change comes with specific additional duties where Chrisco will now be responsible for merging S&P PRs and grooming the issue backlog.
Creating a dedicated team to maintain S&P will centralize the duties and responsibilities involved with the role. The goal is to promote more activity, maintenance, and adoption of standards. A secondary goal in creating specialized teams is to distribute various efforts across the shop to address the current issue where certain team members are overloaded with extracurricular duties. Specifically this will allow Ryeker, …
> Centralizing code ownership to a dedicated maintainers team

- best-practices/client-side/README.md
All the old links get 404ed. None of these links are relevant anymore
1. Removed or replaced links 
Remove or add client side links. Most links went to pages that no longer exist.
Closes #168
> fix(client-side-links): Deprecate client links

- .circleci/config.yml
1. Adds CircleCI to the project.
2. Adds [awesome-bot](https://github.com/dkhamsing/awesome_bot) to the repo.
The awesome bot gem is used to check all .md files recursively and report back if any of the links are incorrect via CircleCI. This will make sure all outside links are still relevant and prevents confusion to developers looking at non-existent links.
Closes #162 
One thing to note, a code owner or someone with access to CircleCI will have to add this project. I currently don't have access.
> feat(awesome-bot): check all available links

- best-practices/server-side/framework/README.md
1. Split Programming Languages from Frameworks
2. Added more resources we use at Shift3
* Breaking out Programming Languages from Frameworks will enable us to navigate a bit better and give general information about the specific concept before diving in to official docs.
* All descriptions have been lifted off wikipedia. 
Closes #172
> refactor(frameworks): Split out languages from frameworks

- best-practices/native/react-native/common-components/phone-number-test.js
- best-practices/native/react-native/common-components/phone-number.js
1. Adds the reusable phone number link component
This component takes in a few props:
- A phone number
- An option to disallow scaling (So adjusting font size on the hardware level doesn't affect the component)
- Some styling options: Color, font size, and line height
It returns text that when pressed opens up an action sheet giving the user the option to either text or call the number through use of the required package, `react-native-action-sheet` (props to @carlosvargas for the find). Links for the package are below.
I recently used this component for Listing Alert, and thought it would be useful enough to go on this component list.
Creating a link to either call or text a phone number is pretty easy, but giving the user the option to do either one is not. Hopefully, this helps a bit. …
> Reusable phone number link component

- README.md
1. Added Link to presentation README in root of project README.
2. Added updated time-frame for presentations
Users are now able to easily navigate to the presentation page and also references our twice a month meeting.
Closes #190
> feature(presentation): Presentation link and timeframe

- .github/PULL_REQUEST_TEMPLATE.md
1. Adds Purpose, Pre-testing TODOs, and Testing Steps sections to the template
The aforementioned sections seemed to have been lost when the template was updated at some point in the past.  I find them quite helpful, and use them 99% of the time, so I figured it would be best to add them back in.
If these were removed intentionally, please let me know.
Closes #204
> feat(pr-template): add helpful sections to pr template

- best-practices/client-side/framework/react/README.md
1. Add intro section in the ReadMe for React  along with links to documentation
2. Add links to existing repos for boilerplates
3. Add links to Jest and Enzyme for information on testing React components
Currently the react ReadMe has no content and we might want to add information regarding boilerplates and testing.
I provided links to existing repositories as an example for running a react based project along with links to documentation.
Closes #208
> feature(react-readme): add content to react readme

- best-practices/development-tools/continuous-integration/react_native.yml
1. Add in working version of a react native CircleCI build
We do not currently have a react native build without expo setup and having a working one would help out on future projects. 
Use working CircleCI build from another project and add it into our S/P repo.
On default, jest is pretty easy to setup initially, but updating it and getting it to work with react native was a challenge. Some of those challenges on the setup side have been documented [here](https://github.com/Shift3/rn-by-example/pull/20). However, the CI portion turned out pretty simple once it was complete. 
Closes #94
> feature(react-native): Working react native without expo setup

- standards/README.md
- standards/git-commands.md
1. Adds a basic description of Git Hooks.
2. Adds a link to websites that already explain git hooks better than I can.
To give developers an introduction to Git Hooks as a concept. 
By adding reference websites that are actively maintained, this readme will be future proof (as long as the websites/references do not disappear). I attempted to go over each of the git hooks and how they could be used within projects at Shift3, but after going through a couple, I realized that I was assuming a LOT when it came to specific setups. It may be better to add specific scripts to boilerplate like projects instead of the S/P repo. Thoughts on this are welcome on this subject!
There are quite a few git hooks that I have never used before and look forward to trying them out in future projects. 
Closes …
> feature(git-hooks): Git Hooks should be referenced

- .circleci/config.yml
1. All Shift3 resources are now whitelisted
2. Removed all specific Shift3 projects
To once and for all fix awesome_bot attempting to retrieve internal resources and 404ing. 
Whitelist any Shift3 resource.
Install gem and run the same commands as the CircleCI job. 
Closes #210
> fix(awesome-whitelist): Whitelist all Shift3 resources from awesome_bot

- README.md
- workshops/README.md
1. Adds workshop description
2. Adds workshop google doc link. Let me know if we have a prefered place for this. Current rights are that anyone from bitwise can edit/view. 
Developers (or any user) should be able get information on workshops as well as past videos/repo links.
Adding a basic description + google doc with specifics. Not sure if we wanted to stay private, so I went with the same standard as the presentation page.
Closes #212
> Workshops - Description and Past Workshop Links

- README.md
- best-practices/development-tools/aws/cloudfront-set-up.sh
- best-practices/development-tools/continuous-integration/circle_ci_config.yml
- best-practices/native/react-native/expo/certificates/README.md
- best-practices/server-side/tools/deploy-changes-since/Deploy-ChangesSince.ps1
- standards/branching.md
- standards/code-versioning.md
- standards/git-commands.md
- standards/issue-template.md
- standards/readme-guidelines.md
1. Blanket changes references from `master` branch to `main` branch.
To change all branch references from master to main on October 1st, the same day GitHub will be changing all new and some existing default branches.
By changing this repo first, we get a head start on the new branch changes that will come into effect shortly.
This will be a Work in Progress until Oct 1st. On October 1st, the WIP will be removed. 
Closes #206
> Master to Main branch

- standards/branching.md
1. Added reference to Staging branch for demos.
2. Added reference to Main branch for production.
Demos should be run based on the staging branch and not the development branch. 
Make explicit references to Development, Staging, and Main branches.
Closes #218
> Development to Staging Branch for Demos

- best-practices/native/react-native/README.md
1. Add link to CircleCI setup and example app
2. Specific to react-native
React Native only has some sparse documentation when it comes to the CI setup. We still need to document a majority of this work so others can move forward quicker when it comes to react-native projects. 
This change shows a non-trivial example of a non-trivial CircleCI setup as well as examples of an android/ios setup. We took some of this to create the current Sundial android setup. 
One doesn't necessarily need the linked orb to move forward with the CI job, but you can still re-use a majority of the commands and setups contained within: https://circleci.com/developer/orbs/orb/react-native-community/react-native 
References #226
> React Native - Example CircleCI docs with orb 

- standards/qa-process.md
1. Is Report of Issues required?
2. Post Sprint Meeting
2a. Closing Milestones
2b. Certificate of Completion 
3. QA will set up Project Board
4. Copying previous acceptance test for new sprint
5. Requesting a New Sprint
_We have already started to use some of these new standards during our QA sprint process. These new standards have helped QA to be more organized as well as giving PM's and devs a better understanding of where testing is during a sprint. This is not the final version of this document. I will be adding necessary links and descriptions after break._
_Optional Post Sprint Meeting gives developers a chance to ask about issues that have been posted before a sprint has officially ended. PM's in need of a Report of Issues can now request that …
> QA SP update 1

- best-practices/native/react-native/deployment/android/README.md
1. Fixes deprecated link to google app console.
Keep our documentation up to date. The publish page no longer exists.
Replaces the publish page with a generic console page. Both now go to the same page in googles "new" app console.  
Closes #240
> Fix links to Google app console

- standards/code-reviews.md
1. Added PR Team needs to be included as potential reviewers for PRs.
To clarify who to request for PR reviews.
The change clarifies who to request for PR reviews.
- [] Spelling/grammar check
- [] Ensure wording is correct
N/A
Adding first PR for onboarding
Closes #244
> fix(code-reviews): Added PR Team as reviewers

- standards/qa-process.md
1. change qa to use the correct mailing list
Makes sure all references to shift3tech within mail lists reference the correct parent email address.
Changes shift3tech to bitwiseindustries.
I am actually surprised we don't have as much references to the different teams here at Bitwise. 
Closes #248
> chore(qa-process): Replace shift3tech to bitwiseindustries

- README.md
- best-practices/development-tools/accessibility/README.md
- best-practices/native/react-native/README.md
- best-practices/native/react-native/rn-by-example/README.md
- best-practices/native/react-native/startup/native-code.md
- best-practices/native/xamarin/README.md
- best-practices/server-side/security/README.md
- presentations/README.md
- standards/README.md
- standards/acceptance-testing.md
- standards/code-reviews.md
- standards/code-versioning.md
- standards/commits.md
- standards/contributing.md
- standards/git-commands.md
- standards/project-setup.md
- standards/qa-process.md
- standards/readme-guidelines.md
- workshops/README.md
1. Rebranded Shift3 to Bitwise
Removed Shift3 references where it made sense to do so.
Replaced Shift3 verbiage with Bitwise. Some of the old projects are still branded as Shift3.
After looking at all the older pages, its apparent we should take a look at some of the older resources and projects. 
Closes #251
> refactor(re-branding): Re-brand Shift3 to Bitwise

- README.md
1. Replace Ryeker with @fluturecode, @gyuhunlee, and @soniaroh contact info.
2. Match the Meeting info to what we are actually doing.
As time has gone on, the S&P meetings have expanded into BW Developer Connect Meetings, which now includes the rest of the organization and its different teams. 
The current info on the S&P readme did not reflect the current status of the meetings. The changes now include more details and the individuals involved with organizing said meetings. 
Side note:
We may want to create an email group (like developerconnect@bitwiseindustries.com) to make things easier in the long run (every gets an email and nothing gets lost).
Closes #254
> fix(meeting-contact): More accurate Bitwise Meetings

- best-practices/development-tools/azure/devops/README.md
- best-practices/development-tools/azure/devops/continuous-integration/azure-app-functions-continuous-integration.md
- best-practices/development-tools/azure/devops/continuous-integration/azure-pipelines-azure-app-functions-ci.yml
- best-practices/development-tools/azure/devops/deployment/aws-elasticbeanstalk/aws-elastic-beanstalk-deployment.md
- best-practices/development-tools/azure/devops/deployment/aws-elasticbeanstalk/azure-pipelines-aws-eb-cd.yml
- best-practices/development-tools/azure/devops/deployment/aws-elasticbeanstalk/azure-pipelines-aws-eb-docker-cd.yml
- best-practices/development-tools/azure/devops/deployment/azure-app-functions/azure-app-functions-deployment.md
- best-practices/development-tools/azure/devops/deployment/azure-app-functions/azure-pipelines-azure-app-functions-cd.yml
1. Add a documentation for using Azure DevOps with CI/CD
2. Add a documentation for using Azure DevOps to deploy azure app functions.
3. Add a documentation for using Azure DevOps to test azure app functions.
4. Add a documentation for using Azure DevOps to deploy .net Core app into AWS elastic beanstalk.
Have some documentations to describe how to use Azure DevOps with CI/CD.
https://stackoverflow.com/questions/53544039/assets-file-project-assets-json-not-found-when-running-a-build-on-azure-devops
https://stackoverflow.com/questions/53727278/devops-hosted-pipeline-fail-to-build-net-core-2-2
https://docs.aws.amazon.com/vsts/latest/userguide/tutorial-eb.html
https://aws.amazon.com/blogs/devops/deploying-a-asp-net-core-web-application-to-amazon-ecs-using-an-azure-devops-pipeline/ …
> doc(azure-devo-ops): Add a documentation for deployment using azure DevOps

- standards/README.md
1. Change broken link for QA Process
QA Process link redirected to 404, did not redirect to readme
This was to practice pull requests per the automated onboarding email.
Also, I know we are supposed to merge to the development branch, but this repo doesn't have one (which I think makes sense) so I chose main.
closes #264
> docs(standards): fix QA Process link

- .circleci/config.yml
1. Remove shift3 blanket blocklist
2. Replace with project/link specific Shift3 url allowlist
Fix issue where internal public facing README links were not linked to an existing page.  
By being very specific with what pages are being blocked from awesome_bot, we reduce the number of possible false positives. 
Pull down the repo.
run `bundle exec awesome_bot --allow-redirect --allow-dupe -w awesome_bot --allow-redirect --allow-dupe -w https://github.com/Shift3/ifg/compare/v0.4.0...v0.5.0,https://github.com/Shift3/sinclair-scanner-application,https://github.com/Shift3/sinclair-scanner-application/pull/137,https://github.com/Shift3/FUSDMonitoringAppXamarin,https://github.com/Shift3/rn-by-example,https://github.com/Shift3/fusd-front-desk-kiosk,regexr,https://github.com/Shift3/bw-project-status …
> fix(link-check): remove awesome_bot github whitelist

- README.md
1. Add in slack channels and other references for help with blockers.
Make developers aware of our slack channels that can help them out. 
Add in the start of the basic slack channels that we have available within the org. 
If anyone knows of some good BW specific slack channels, resources, outreach comment below and we can add it to the list! I can see this becoming another page eventually. 
Closes #273
> feat(README): Internal Resources for help

- best-practices/client-side/framework/react/README.md
1. Add a link to Digital Ocean's guide to using React Developer Tools (RDT)
RDT is available to help React devs debug their programs, but it is a bit unclear how to use this tool.  #261 
Digital Ocean's guide to using RDT is quite good, and should help devs get more familiar with this tool.
Closes #261
> Update React Docs - RDT Guide

- README.md
1. removed commas and added semicolons in areas that needed correction
2. Employees' names were not opening the default email. It was leading the user to a 404 error page when clicked on. Added `mailto:`
The purpose of this was to allow the user to open their default mail and message the person they have clicked on in the document. 
Users wouldn't be redirected to a 404 error page.
Learned more about markdown! I also got to use a plugin called Markdown Preview Enhanced to preview my markdown in visual studio code. 
I also wanted to know if shift3 workspace is still being used? The document states that we should be using it but we are using bitwiseindustries and also #shift-3-technical-discussions channel was rename to #bwtc-technical-discussions. Should that be updated as well?
> docs(README.md): fixed typos

- standards/commits.md
1. Updates doc for commit message standards
2. Includes sections on conventions and tools
3. Cleaned up the markdown with markdown linter
See result: https://github.com/amerikan/standards-and-practices/blob/main/standards/commits.md
To provide better information as to why good commit messages matter and also some tools that can help enforce a particular convention.
_If this closes an issue, name it here. If it doesn't, remove this line_
> docs(commits): update with commit messages information

- standards/git-commands.md
Adds two lesser known commands to appropriate section in git-commands
1. switch
2. restore
The checkout command is an overloaded workhorse and some of the functions are incredibly useful but not very intuitive to use and understand. This is why, in 2019, switch and restore were created in an effort to make using git more intuitive. These commands may be more accessible to newer git users.
Links to official documentation provide more detail on the use of these commands:
https://git-scm.com/docs/git-switch
https://git-scm.com/docs/git-restore
Closes #287
> docs(git-commands): Add switch and restore cmd descriptions

- .github/ISSUE_TEMPLATE/epic-issue-template.md
1. Remove "Issue" prefix from listed issues
#289 
GitHub has a new integration for linking issues that looks quite nice.  The "Issue" prefix is now unnecessary.
> Update Epic Issue Template

- standards/README.md
- standards/branch-protections.md
1. New branch protections readme
2. Update to master list on standards
This README provides guidance and recommendations regarding the GitHub branch protections as well as team assignment to repos. This standard enforces branch protection on the development branch and main branches on projects to prevent accidental pushes to each branch. It seems to work pretty well on our other boilerplate projects.
Adds images and step by step instructions to set up branch protections on a repo.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-pro …
> feature(branch-protections): Team leads should be able to apply branch protections

- standards/qa-process.md
QA is now requesting the scope of work and a list of known issues before the kickoff meeting. We are also emphasizing the importance of an acceptance test and clarifying that the developers will create the project boards and milestones with the definition of done. QA will assist and guide the developers through those if needed during the kickoff meeting.
1. PM will provide Scope of Work and List of Know Issues when scheduling QA
2. Expressing the importance of an acceptance test to encourage the developers to do it and reach out to QA for assistance 
3. Clarifying that the developers will be the ones to create and manage the projects boards, and create the milestone for this sprint with the definition of done. If the developer does not do this before …
> QA SP update 3

- best-practices/server-side/framework/python/django/lessons-learned-from-ultra-gro-deployment.md
1. Remove non-working sandbox link
Our CI builds are failing because one of our links is 404ing. 
Remove offending link (after discussion with Devops). The project is no longer supporting a sandbox. 
Closes #334
> fix(lessons-learned): Remove old sandbox link

- README.md
1. Modified "Need Help" section within the S&P repo to have links to resources.
2. Our specific stack overflow instance is now referenced within the "Need Help" section.
One of the pain points we have as an organization is not archiving questions and discussions within slack. 
Stack Overflow has traditionally been a resource developers go to for longstanding and specific issues.
Closes #332
> doc(readme): Developers should know about our stack overflow account

- README.md
1. Change Guidebook and Handbook for a bit more differentiation. 
2. Item 2
Differentiate between BW Handbook/BWTC Guidebook
Changes the text but keep the url the same.
Closes #337
> fix(README): Differentiate between BW Handbook/BWTC Guidebook

- standards/developer-accountability.md
1.  correct left angle brackets in checkbox 6
2. correct 'defense' typo in checkbox 9
- the angled brackets were not rendering correctly. instead of `<`, it was `&lt;`
- correct spelling errors
- double check `&lt;` was meant to represent the left angled bracket
- double check spelling of typos
n/a
read over sections with changes
Closes #343
> Bc 343 dev accountability typos

- standards/code-reviews.md
1. add link to BWTC dev connect on code review
2. add link to Google article emphasizing code review speed
#369 
This pr adds links to the resources section of the code review page. Applicable outside information was found that could be considered supplemental to our standards for code review, and find a good place here.  
Additional links and resources bolster the strength of our standards, provided that the organization agrees with them.  
NA
View the links and assess their value in including them in our S&P repo.
Learning to navigate through the S&P and find places where I can contribute was the majority of this feature, and I'm looking forward to additional contributions I can make. 
Closes #369
> feat(#369, code-reviews): Add additional resource links

- standards/contributing-outside-organization.md
- standards/developer-accountability.md
- standards/issue-template.md
1. Links to local markdown files changed from external(https://...) to local(./...)
The links were difficult to navigate in VS Code and inconsistent with a majority of absolute or relative paths
Using relative paths to replace links found only inside standards
- [] Right click and preview relevant files
Click on relevant links, observe navigation within preview
Didn't know you could link .md files and navigate them in this fashion
Closes #372
> chore(standards): find and change web links to relative links

- best-practices/development-tools/accessibility/README.md
Supersedes #368 
1. Correct grammatical errors and typos on README doc
Multiple grammatical errors and a couple typos
N/A
Read over README doc
Closes #367
> docs(accessibility readme): resolve typos and grammatical errors

- best-practices/native/nativescript/images.md
1. remove manual link as it no longer works
The site nativescript.rocks no longer works, so any linked resources have been breaking.  
Removed deprecated instructions that no longer go anywhere.  
Blog post describing change: https://fluentreports.com/blog/?p=1434
Closes #376
> fix(nativescript-images): Remove deprecated image platform

- .github/dependabot.yml
1. Make dependabot only look at updates once a month and only on the main branch. 
Most of the gems we use do not need to be updated more than once a month. We were getting bombarded with dependabot updates and we only use one library for checking urls. There is not a huge attack vector on our ci/cd jobs.
Make dependabot check and auto update every month. 
Closes #317
> fix(dependabot): Update dependencies automatically monthly
